############################
#                          #
# undertow properties      #
#                          #
############################
server:
  port: 8080
  forward-headers-strategy: native
  ############################
  #                          #
  # undertow properties      #
  #                          #
  ############################
  ##############################################################################
  # Propiedades a revisar por los desarrolladores del proyecto                 #
  # undertow.threads.io: Numero de hilos de I/O.                               #
  #   Debe establecerse el valor segun la formula: numero.cpus.logicas * 2     #
  #   En openshift el valor numero.cpus.logicas viene dado por el parametro    #
  #   request.cpu del deploymentConfig del aplicativo.                         #
  #   Es necesario establecer este valor POR ENTORNO OPENSHIFT ya que el       #
  #   parametro request.cpu es diferente en cada entorno                       #
  #                                                                            #
  # undertow.threads.worker: Numero de hilos de servicio                       #
  #   Debe establecerse el valor segun la formula: undertow.threads.io * 8     #
  #   Es necesario establecer este valor POR ENTORNO OPENSHIFT ya que el       #
  #   parametro undertow.threads.io es diferente en cada entorno               #
  ##############################################################################
  undertow:
    threads:
      # numero.cpus.logicas * 2
      # !!! reviar por entorno !!!
      io: 4
      # undertow.threads.io * 8
      # !!! reviar por entorno !!!
      worker: 32
  error:
    # Include the "exception" attribute. default false
    include-exception: true
    # When to include a "stacktrace" attribute. default never
    include-stacktrace: always
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
    session:
      cookie:
        http-only: true
        secure: true
        same-site: strict
  ssl:
    enabled: false

###########################################################
#                                                         #
# springdoc properties                                    #
#                                                         #
# WARNING! springdoc solo soporta OpenAPI Specification 3 #
# deshabilitar en caso de que se utilice otra versión     #
#                                                         #
###########################################################
springdoc:
  api-docs:
    enabled: true

#############################
#                           #
# spring general properties #
#                           #
#############################
spring:
  mandatory-file-encoding: UTF-8
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: false
  application:
    name: example-app-11
  banner:
    location: classpath:santalucia-banner.txt
  mvc:
# Whether logging of (potentially sensitive) request details at DEBUG and TRACE
    log-request-details: false
  web:
    locale-resolver: accept-header
# default locale used when no Accept-Language is send
    locale: es_ES
  output:
    ansi:
      enabled: detect
  jmx:
    enabled: false
    unique-names: true
  devtools:
    livereload:
      enabled: true

######################################
#                                    #
# cloud properties                   #
#                                    #
######################################
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false
      config:
        name: ${spring.application.name}
######################################
#                                    #
# internationalization properties    #
#                                    #
######################################

  messages:
    basename: classpath:i18n/messages
    # si no se especifica se cachean para siempre. Al
    # estar en el jar no es correcto
    #cache-duration: 1s
    encoding: UTF-8
    fallback-to-system-locale: false

######################################
#                                    #
# datasource properties              #
#                                    #
######################################
  datasource:
    primary:
      hikari:
        driver-class-name: com.informix.jdbc.IfxDriver
        pool-name: informix-pool
        jdbc-url: jdbc:informix-sqli://slbdifxd15.servidores.net:20101/siis:INFORMIXSERVER=fun_jdbc
    secondary:
      hikari:
        driver-class-name: oracle.jdbc.OracleDriver
        pool-name: oracle-pool
        jdbc-url: jdbc:oracle:thin:@slbdorad15.servidores.net:1548/DB12UTF8D.DES.SANTALUCIA.ES

######################################
#                                    #
# security properties                #
#                                    #
######################################
  security:
    oauth2:
      resourceserver:
        jwt: #para habilitar la validacion local del token
          # posibles valores RS256,RS512 depende del realm
          jws-algorithms: RS256
          jwk-set-uri: https://sso-sldev.santalucia.es/auth/realms/3scale/protocol/openid-connect/certs
          # OpenID Connect Provider URI asserts as its Issuer Identifier
          issuer-uri: https://sso-sldev.santalucia.es/auth/realms/3scale

###########################
#                         #
# santalucia properties   #
#                         #
###########################
santalucia:
  ams:
    features:
      core:
        default-zone-id: ${TZ:Europe/Madrid}
        entorno: dev
      micrometer:
        jvm-extras:
          process-memory-metrics:
            enabled: false
          process-thread-metrics:
            enabled: false
        hikari:
          enabled: true
      guardium:
        enabled: true
      feign:
        base-packages: com.santalucia
      mybatis:
        primary:
          lazy-initialization: true
          configuration:
            lazy-loading-enabled: true
          base-packages:
          - com.santalucia.example.infrastructure.mybatis.primary
        secondary:
          lazy-initialization: true
          configuration:
            lazy-loading-enabled: true
          base-packages:
          - com.santalucia.example.infrastructure.mybatis.secondary
      security:
        core:
          enabled: true
        cors:
          enabled: true
          allowed-origins:
          - http://localhost:8080
        csrf:
          enabled: true
        xss:
          enabled: true
        oauth2:
          token-propagation: true
        actuator:
          unsecured-end-points:
          - info
          - health
          - metrics
          - startup

###########################
#                         #
# feign client properties #
#                         #
###########################
helloworld:
  url: http://localhost:8080/hello-world/v1
###########################
#                         #
# logging properties      #
#                         #
###########################

logging:
  level:
    root: INFO
    "[com.santalucia]": DEBUG
    "[org.springframework]": INFO
    "[org.springframework.test]": DEBUG
    #"[org.springframework.web.servlet]": DEBUG
    #"[org.springframework.security]": DEBUG
    #"[org.springframework.web.client]": DEBUG
    #trazas para mostrar los errores de login debido a que salen en modo debug
    "[org.springframework.security.oauth2.server.resource]": DEBUG
    #Paquete que indica cuando SB esta disponible
    "[org.springframework.boot.availability]": DEBUG

###########################
#                         #
# micrometer properties   #
#                         #
###########################
management:
  metrics:
    tags:
      #Needed by micrometer +1.1.0
      application: ${spring.application.name}

###########################
#                         #
# info properties         #
#                         #
###########################
info:
  app:
    name: ${spring.application.name}
    encoding: UTF-8
    java:
      source: 17
      target: 17
---
#Profile habilitado de forma automatica cuando se despliega en OCP
spring:
  config:
    import:
    - optional:classpath:monitoring.yaml
    - optional:classpath:tracing.yaml
    activate:
      on-profile:
      - kubernetes
  banner:
    location: classpath:santalucia-banner.json
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: false

---
#Profile habilitado de forma automatica cuando se compila en jenkins
spring:
  config:
    activate:
      on-profile:
      - devops
  cloud:
    kubernetes:
      enabled: false
