############################
#                          #
# undertow properties      #
#                          #
############################
server:
  port: 8080
  forward-headers-strategy: native
  ############################
  #                          #
  # undertow properties      #
  #                          #
  ############################
  ##############################################################################
  # Propiedades a revisar por los desarrolladores del proyecto                 #
  # undertow.threads.io: Numero de hilos de I/O.                               #
  #   Debe establecerse el valor segun la formula: numero.cpus.logicas * 2     #
  #   En openshift el valor numero.cpus.logicas viene dado por el parametro    #
  #   request.cpu del deploymentConfig del aplicativo.                         #
  #   Es necesario establecer este valor POR ENTORNO OPENSHIFT ya que el       #
  #   parametro request.cpu es diferente en cada entorno                       #
  #                                                                            #
  # undertow.threads.worker: Numero de hilos de servicio                       #
  #   Debe establecerse el valor segun la formula: undertow.threads.io * 8     #
  #   Es necesario establecer este valor POR ENTORNO OPENSHIFT ya que el       #
  #   parametro undertow.threads.io es diferente en cada entorno               #
  ##############################################################################
  undertow:
    threads:
      # numero.cpus.logicas * 2
      # !!! reviar por entorno !!!
      io: 4
      # undertow.threads.io * 8
      # !!! reviar por entorno !!!
      worker: 32
  error:
    # Include the "exception" attribute. default false
    include-exception: true
    # When to include a "stacktrace" attribute. default never
    include-stacktrace: always
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
    session:
      cookie:
        http-only: true
        secure: true
        same-site: strict
  ssl:
    enabled: false

###########################################################
#                                                         #
# springdoc properties                                    #
#                                                         #
# WARNING! springdoc solo soporta OpenAPI Specification 3 #
# deshabilitar en caso de que se utilice otra versión     #
#                                                         #
###########################################################
springdoc:
  api-docs:
    enabled: true

#############################
#                           #
# spring general properties #
#                           #
#############################
spring:
  mandatory-file-encoding: UTF-8
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: false
  application:
    name: example-app-11
  banner:
    location: classpath:santalucia-banner.txt
  mvc:
# Whether logging of (potentially sensitive) request details at DEBUG and TRACE
    log-request-details: false
  web:
    locale-resolver: accept-header
# default locale used when no Accept-Language is send
    locale: es_ES
  output:
    ansi:
      enabled: detect
  jmx:
    enabled: false
    unique-names: true
  devtools:
    livereload:
      enabled: true

######################################
#                                    #
# cloud properties                   #
#                                    #
######################################
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false
      config:
        name: ${spring.application.name}
######################################
#                                    #
# internationalization properties    #
#                                    #
######################################

  messages:
    basename: classpath:i18n/messages
    # si no se especifica se cachean para siempre. Al
    # estar en el jar no es correcto
    #cache-duration: 1s
    encoding: UTF-8
    fallback-to-system-locale: false

######################################
#                                    #
# datasource properties              #
#                                    #
######################################
  datasource:
    primary:
      hikari:
        driver-class-name: com.informix.jdbc.IfxDriver
        pool-name: informix-pool
        jdbc-url: jdbc:informix-sqli://slbdifxd15.servidores.net:20100/siis:INFORMIXSERVER=fun_jdbc
        # jdbc-url: jdbc:informix-sqli://INFORMIXSERVER=fun_tcp;DATABASE=siis;SQLH_TYPE=FILE;SQLH_FILE=/deployments/config/sqlhosts
        # leakDetectionThreshold: (milisegundos) Muestra en el log si una
        #   conexión del pool lleva más de 10 segundos en uso.
        leak-detection-threshold: 10000
        # register-mbeans: Habilita que se pueda ver el pool en Dynatrace.
        register-mbeans: true
        # keepalive-time: (milisegundos) "Ping" de aplicación, a nivel 7.
        #   2 paquetes C->S y 1 paquete S->C
        keepalive-time: 120000
        # connection-init-sql: Para que se valide la conexión en la
        #   fase de creación.
        connection-init-sql: SELECT 1
        # connection-timeout: (milisegundos) Tiempo de espera del código de
        #   usuario para obtener un objeto de conexión idle del pool. NO es el
        #   tiempo de espera de la conexión TCP.
        connection-timeout: 10000
        # minimumIdle: Número mínimo de conexiones inactivas que se mantendrán
        #   en el pool.
        #minimumIdle: 10
        # maximumPoolSize: Número máximo de conexiones que se mantendrán en el
        #   pool.
        #maximumPoolSize: 10
        # maxLifetime: (milisegundos) Tiempo máximo de vida de una conexión en
        #   el pool. Si una conexión lleva más de 30 minutos en el pool, se
        #   cierra y se crea una nueva.
        max-lifetime: 1740000
        # Propiedades de conexión adicionales específicas del driver de Informix
        data-source-properties:
          # IFX_SOC_TIMEOUT: (milisegundos) Tiempo máximo de espera TCP de la
          #   conexión a la base de datos. Afecta en la fase de conexión y en
          #   las fases de ejecución de las sentencias SQL!!!
          #"[IFX_SOC_TIMEOUT]": 10000
          # LOGINTIMEOUT: (milisegundos) Tiempo máximo de espera para la
          #   autenticación del usuario en la base de datos. No se observa
          #   efecto cuando se usa CP junto a INFORMIXCONTIME
          #"[LOGINTIMEOUT]": 5000
          # INFORMIXCONTIME: (segundos) Tiempo máximo de espera TCP para la
          #   conexión inicial a la base de datos. No afecta en las fases de
          #   ejecución de las sentencias SQL
          "[INFORMIXCONTIME]": 5
          # INFORMIXCONRETRY: Número de reintentos de conexión a la base de
          #   datos en caso de fallo. Por defecto es 0. Al usar CP, es Hikari
          #   quien se encarga de los reintentos.
          # "[INFORMIXCONRETRY]": 3
          # IFX_SOC_KEEPALIVE: (boolean) Habilita el keepalive, a nivel 4,
          #   añadiendo SO_KEEPALIVE al socket de la conexión TCP.
          "[IFX_SOC_KEEPALIVE]": true
    secondary:
      hikari:
        driver-class-name: oracle.jdbc.OracleDriver
        pool-name: oracle-pool
        # TRANSPORT_CONNECT_TIMEOUT: (segundos) Tiempo máximo de espera TCP
        # CONNECT_TIMEOUT: (segundos) Tiempo máximo de espera al crear la
        #   sesiónn de la base de datos.
        #jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(TRANSPORT_CONNECT_TIMEOUT=3)(CONNECT_TIMEOUT=5)(ADDRESS_LIST=(ADDRESS=(HOST=slbdorad15.servidores.net)(PORT=1548)(PROTOCOL=tcp)))(CONNECT_DATA=(SERVICE_NAME=DB12UTF8D.DES.SANTALUCIA.ES)))
        jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=5)(RETRY_COUNT=4)(RETRY_DELAY=2)(TRANSPORT_CONNECT_TIMEOUT=3)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=slbdorad15.servidores.net)(PORT=1548)))(CONNECT_DATA=(SERVICE_NAME=DB12UTF8D.DES.SANTALUCIA.ES)))
        # register-mbeans: Habilita que se pueda ver el pool en Dynatrace.
        register-mbeans: true
        # keepalive-time: (milisegundos) "Ping" de aplicación, a nivel 7.
        #   2 paquetes C->S y 1 paquete S->C
        keepalive-time: 120000
        # connection-init-sql: Para que se valide la conexión en la
        #   fase de creación.
        #   En Oracle no se puede usar "SELECT 1". Failed to initialize pool:
        #   ORA-00923: FROM keyword not found where expected
        connection-init-sql: SELECT 1 FROM DUAL
        # connection-timeout: (milisegundos) Tiempo de espera del código de
        #   usuario para obtener un objeto de conexión idle del pool. NO es el
        #   tiempo de espera de la conexión TCP.
        connection-timeout: 10000
        # leakDetectionThreshold: (milisegundos) Muestra en el log si una
        #   conexión del pool lleva más de 10 segundos en uso.
        leak-detection-threshold: 10000
        # minimumIdle: Número mínimo de conexiones inactivas que se mantendrán
        #   en el pool.
        #minimumIdle: 10
        # maximumPoolSize: Número máximo de conexiones que se mantendrán en el
        #   pool.
        #maximumPoolSize: 10
        # maxLifetime: (milisegundos) Tiempo máximo de vida de una conexión en
        #   el pool. Si una conexión lleva más de 30 minutos en el pool, se
        #   cierra y se crea una nueva.
        max-lifetime: 1740000
        data-source-properties:
          "[oracle.jdbc.defaultConnectionValidation]": COMPLETE
######################################
#                                    #
# security properties                #
#                                    #
######################################
  security:
    oauth2:
      resourceserver:
        jwt: #para habilitar la validacion local del token
          # posibles valores RS256,RS512 depende del realm
          jws-algorithms: RS256
          jwk-set-uri: https://sso-sldev.santalucia.es/auth/realms/3scale/protocol/openid-connect/certs
          # OpenID Connect Provider URI asserts as its Issuer Identifier
          issuer-uri: https://sso-sldev.santalucia.es/auth/realms/3scale

###########################
#                         #
# santalucia properties   #
#                         #
###########################
santalucia:
  ams:
    features:
      core:
        default-zone-id: ${TZ:Europe/Madrid}
        entorno: dev
      micrometer:
        jvm-extras:
          process-memory-metrics:
            enabled: false
          process-thread-metrics:
            enabled: false
        hikari:
          enabled: true
      guardium:
        enabled: true
      feign:
        base-packages: com.santalucia
      mybatis:
        primary:
          lazy-initialization: true
          configuration:
            lazy-loading-enabled: true
          base-packages:
          - com.santalucia.example.infrastructure.mybatis.primary
        secondary:
          lazy-initialization: true
          configuration:
            lazy-loading-enabled: true
          base-packages:
          - com.santalucia.example.infrastructure.mybatis.secondary
      security:
        core:
          enabled: true
        cors:
          enabled: true
          allowed-origins:
          - http://localhost:8080
        csrf:
          enabled: true
        xss:
          enabled: true
        oauth2:
          token-propagation: true
        actuator:
          unsecured-end-points:
          - info
          - health
          - metrics
          - startup

###########################
#                         #
# feign client properties #
#                         #
###########################
helloworld:
  url: http://localhost:8080/hello-world/v1
###########################
#                         #
# logging properties      #
#                         #
###########################

logging:
  level:
    root: INFO
    "[com.santalucia]": DEBUG
    "[org.springframework]": INFO
    "[org.springframework.test]": DEBUG
    #"[org.springframework.web.servlet]": DEBUG
    #"[org.springframework.security]": DEBUG
    #"[org.springframework.web.client]": DEBUG
    #trazas para mostrar los errores de login debido a que salen en modo debug
    "[org.springframework.security.oauth2.server.resource]": DEBUG
    #Paquete que indica cuando SB esta disponible
    "[org.springframework.boot.availability]": DEBUG
    com.zaxxer.hikari: DEBUG # En todos los entornos a DEBUG

###########################
#                         #
# micrometer properties   #
#                         #
###########################
management:
  metrics:
    tags:
      #Needed by micrometer +1.1.0
      application: ${spring.application.name}

###########################
#                         #
# info properties         #
#                         #
###########################
info:
  app:
    name: ${spring.application.name}
    encoding: UTF-8
    java:
      source: 17
      target: 17
---
#Profile habilitado de forma automatica cuando se despliega en OCP
spring:
  config:
    import:
    - optional:classpath:monitoring.yaml
    - optional:classpath:tracing.yaml
    activate:
      on-profile:
      - kubernetes
  banner:
    location: classpath:santalucia-banner.json
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: false
logging:
  structured:
    format:
      console: ecs
      file: ecs

---
#Profile habilitado de forma automatica cuando se compila en jenkins
spring:
  config:
    activate:
      on-profile:
      - devops
  cloud:
    kubernetes:
      enabled: false
