
    


server:
  port: 8080
  error:
    include-exception: true # Include the "exception" attribute. default false
    include-stacktrace: always # When to include a "stacktrace" attribute. default never
    include-binding-errors: always
    include-message: always
    whitelabel:      enabled: true
  compression:
    enabled: true
#  forward-headers-strategy: native #default is ncsa 
  http2:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
    session:
      cookie:
        http-only: true
        secure: true
  ssl:
    enabled: false
#    ciphers: TLS_RSA_WITH_AES_128_CBC_SHA256, INCLUDE_ANY_OTHER_ONES_YOU_NEED_TO_SUPPORT
#    protocol: TLS
#    enabled-protocols: TLSv1.2

springfox:
  documentation:
    open-api:      enabled: false #disable openapi3 core, all specs are openapi2 
    enabled: true


spring:
  main:
    allow-bean-definition-overriding: true
  mvc: 
    log-request-details: true # Whether logging of (potentially sensitive) request details at DEBUG and TRACE level is allowed.
    locale-resolver: accept-header
    locale: fr_FR #default locale used when no Accept-Language is send
  output:
    ansi:
      enabled: detect
  jmx:
    enabled: true
    unique-names: true 
  devtools:    livereload:      enabled: true
 
## internacionalizacion
  messages:
    basename: i18n/messages
    #cache-duration: 1s
    encoding: UTF-8
    fallback-to-system-locale: false
    #default-locale: fr_FR #custom
       
    
  security:
    oauth2:
      resourceserver:
        jwt: #para habilitar la validacion 
          jws-algorithm: RS256 #posibles valores RS256,RS512 depende del realm
          jwk-set-uri: https://sso-sldev.santalucia.es/auth/realms/3scale/protocol/openid-connect/certs
          issuer-uri: https://sso-sldev.santalucia.es/auth/realms/3scale # URI that an OpenID Connect Provider asserts as its Issuer Identifier.
#        opaquetoken: #si se quiere validar cada request contra rhsso y el end-point instrospect
#          introspection-uri: https://sso-sldev.santalucia.es/auth/realms/stl-int/protocol/openid-connect/token/introspect
#          client-id: nacho-test-sb2-oauth2
#          client-secret: 397afcf0-9d30-4b19-bf9f-f8b57d7620bc
          
          
#      client: en caso que se quiera configurar el flujo code, no soportado por el back
#        registration: 
#          keycloak:   
#            client-id: nacho-test-sb2-oauth2
#            client-secret: 397afcf0-9d30-4b19-bf9f-f8b57d7620bc
#        provider: 
#          keycloak:
#            issuer-uri: https://sso-sldev.santalucia.es/auth/realms/stl-int/.well-known/openid-configuration
            
  # Conexion para recuperar agencias en pruebas de componente database

  datasource:
    primary:
      hikari:
        driver-class-name: com.informix.jdbc.IfxDriver
        username: amsdacom
        password: Am5Spr1ngD4c0m
        pool-name: InformixCP
        jdbc-url: jdbc:informix-sqli://192.168.204.226:20101/siis:INFORMIXSERVER=fun_jdbc
    secondary:
      hikari:
        driver-class-name: oracle.jdbc.OracleDriver
        username: LAB_ARQ_SW_DEV
        password: lab_arq_sw_dev
        pool-name: OracleCP
        jdbc-url: jdbc:oracle:thin:@slbdorad15.servidores.net:1548/DB12UTF8D.DES.SANTALUCIA.ES 



     
###########################
#                         #
# santalucia properties   #
#                         #
###########################  
santalucia:
  ams:
    features:
      guardium:
        enabled: true
      feign:
        base-packages: com.santalucia.example.api.client
      mybatis:
        primary:
          base-packages: com.santalucia.example.infrastructure.mybatis.primary
        secondary:
          base-packages: com.santalucia.example.infrastructure.mybatis.secondary      security:
        core:          enabled: true        cors:          enabled: true
          allowed-origins: 
            - http://localhost:8080
        csrf:          enabled: true
        xss:
          enabled: true
        oauth2:          token-propagation: true
        actuator:          unsecured-end-points:
            - info
            - health
            - metrics

###########################
#                         #
# feign client properties #
#                         #
###########################
        
helloWorld:
  url: http://localhost:8080/hello-world/v1
      
###########################
#                         #
# logging properties      #
#                         #
###########################
      
logging:
  level:
    root: INFO
    com.santalucia: DEBUG
    org.springframework: INFO
    com.santalucia.arq.ams.componentes.database.guardium.interceptor.GuardiumMyBatisInterceptor: DEBUG
    #org.springframework.web.servlet: DEBUG
    #org.springframework.security: DEBUG
    #org.springframework.web.client: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG #trazas para mostrar los errores de login debido a que salen en modo debug
