server:
  port: 8080
  error:
    include-exception: true # Include the "exception" attribute. default false
    include-stacktrace: always # When to include a "stacktrace" attribute. default never
  compression:
    enabled: true
#  forward-headers-strategy: native #default is ncsa 
  http2:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
    session:
      cookie:
        http-only: true
        secure: true
  ssl:
    enabled: false
#    ciphers: TLS_RSA_WITH_AES_128_CBC_SHA256, INCLUDE_ANY_OTHER_ONES_YOU_NEED_TO_SUPPORT
#    protocol: TLS
#    enabled-protocols: TLSv1.2

spring:
  main:
    allow-bean-definition-overriding: true
  mvc: 
    log-request-details: true # Whether logging of (potentially sensitive) request details at DEBUG and TRACE level is allowed.
  output:
    ansi:
      enabled: detect
  #mandatory-file-encoding: UTF-8 #desactivar en Windows
  jmx:
    enabled: true
    unique-names: true
    
  security:
    oauth2:
      resourceserver:
        jwt: #para habilitar la validacion 
          jws-algorithm: RS256 #posibles valores RS256,RS512 depende del realm
          jwk-set-uri: https://sso-sldev.santalucia.es/auth/realms/3scale/protocol/openid-connect/certs
          issuer-uri: https://sso-sldev.santalucia.es/auth/realms/3scale # URI that an OpenID Connect Provider asserts as its Issuer Identifier.
#        opaquetoken: #si se quiere validar cada request contra rhsso y el end-point instrospect
#          introspection-uri: https://sso-sldev.santalucia.es/auth/realms/stl-int/protocol/openid-connect/token/introspect
#          client-id: nacho-test-sb2-oauth2
#          client-secret: 397afcf0-9d30-4b19-bf9f-f8b57d7620bc
          
          
#      client: en caso que se quiera configurar el flujo code, no soportado por el back
#        registration: 
#          keycloak:   
#            client-id: nacho-test-sb2-oauth2
#            client-secret: 397afcf0-9d30-4b19-bf9f-f8b57d7620bc
#        provider: 
#          keycloak:
#            issuer-uri: https://sso-sldev.santalucia.es/auth/realms/stl-int/.well-known/openid-configuration
            
  # Conexion para recuperar agencias en pruebas de componente database
  datasource:
    informix:
      driver-class-name: com.informix.jdbc.IfxDriver
      url: jdbc:informix-sqli://192.168.204.226:20101/siis:INFORMIXSERVER=fun_jdbc
      username: amsdacom
      password: Am5Spr1ngD4c0m
      configuration:
        pool-name: InformixCP
        connection-timeout: 10000
        idle-timeout: 300000
        max-lifetime: 600000
        
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@slbdorad11.servidores.net:1548/DB12UTF8D.DES.SANTALUCIA.ES
      username: LAB_ARQ_SW_DEV
      password: lab_arq_sw_dev
      configuration:
        pool-name: OracleCP
        connection-timeout: 10000
        idle-timeout: 300000
        max-lifetime: 600000
      

opentracing:
  jaeger:
    enabled: true
    log-spans: true
    http-sender:
       url: https://jaeger-collector-lab-arquitectura-dev.app-dev.santalucia.net/api/traces


management:
  trace:
    http:
      enabled: true # Whether to enable HTTP request-response tracing.
      include: request-headers,response-headers,cookie-headers # Items to be included in the trace.
  endpoint:
    metrics: 
      enabled: true
  metrics:
    tags:
       application: ${spring.application.name} #Needed by micrometer +1.1.0
    export:
 #     dynatrace:
 #       api-token: YOUR_TOKEN
 #       device-id: YOUR_DEVICE_ID
 #       dynatrace.uri: YOUR_URI
 #       step: 5s
      prometheus:
        enabled: true   
  endpoints:
    enabled-by-default: true # Whether to enable or disable all endpoints by default.
    web:
      exposure:
       include: "*"
#      exclude:
#        include: env,beans
     
###########################
#                         #
# santalucia properties   #
#                         #
###########################
    
santalucia:
  ams:
    features:
      guardium:
        enabled: true      security:
        core:          enabled: true        cors:          enabled: false
          #allowed-origins: https://example.com
          #allowed-methods: GET, POST
        csrf:          enabled: false
        oauth2:          token-propagation: true
           
        #actuator:        #  unsecure-end-points:


###########################
#                         #
# feign client properties #
#                         #
###########################
        
helloWorld:
  url: http://localhost:8080/hello-world/v1
      
###########################
#                         #
# logging properties      #
#                         #
###########################
      
logging:
  level:
    root: INFO
    com.santalucia: DEBUG
    org.springframework: INFO
    #org.springframework.web.servlet: DEBUG
    #org.springframework.security: DEBUG
    #org.springframework.web.client: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG #trazas para mostrar los errores de login debido a que salen en modo debug
