#Reference de propiedades
server:
  port: 8080
  error:
    # Include the "exception" attribute. default false
    include-exception: true
    # When to include a "stacktrace" attribute. default never
    include-stacktrace: always
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: true
  compression:
    enabled: true
#  forward-headers-strategy: native #default is ncsa
  http2:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
    session:
      cookie:
        http-only: true
        secure: true
  ssl:
    enabled: false

springfox:
  documentation:
    open-api:
      # disable openapi3 core, all specs are openapi2
      enabled: false
    enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
# Whether logging of (potentially sensitive) request details at DEBUG and TRACE
    log-request-details: true
  web:
    locale-resolver: accept-header
# default locale used when no Accept-Language is send
    locale: es_ES
  output:
    ansi:
      enabled: detect
  jmx:
    enabled: true
    unique-names: true
  devtools:
    livereload:
      enabled: true

## internacionalizacion
  messages:
    basename: classpath:i18n/messages
    # si no se especifica se cachean para siempre. Al
    # estar en el jar no es correcto
    #cache-duration: 1s
    encoding: UTF-8
    fallback-to-system-locale: false

  security:
    oauth2:
      resourceserver:
        jwt: #para habilitar la validacion local del token
          # posibles valores RS256,RS512 depende del realm
          jws-algorithm: RS256
          jwk-set-uri: https://sso-sldev.santalucia.es/auth/realms/3scale/protocol/openid-connect/certs
          # OpenID Connect Provider URI asserts as its Issuer Identifier
          issuer-uri: https://sso-sldev.santalucia.es/auth/realms/3scale

  # Conexion para recuperar agencias en pruebas de componente database

###########################
#                         #
# santalucia properties   #
#                         #
###########################
santalucia:
  ams:
    features:
      guardium:
        enabled: true
      feign:
        base-packages: com.santalucia.example.api.client
      mybatis:
        primary:
          base-packages: com.santalucia.example.infrastructure.mybatis.primary
        secondary:
          base-packages: com.santalucia.example.infrastructure.mybatis.secondary
      security:
        core:
          enabled: false
        cors:
          enabled: true
          allowed-origins:
            - http://localhost:8080
        csrf:
          enabled: true
        xss:
          enabled: true
        oauth2:
          token-propagation: true
        actuator:
          unsecured-end-points:
            - info
            - health
            - metrics

###########################
#                         #
# feign client properties #
#                         #
###########################

helloWorld:
  url: http://localhost:8080/hello-world/v1

###########################
#                         #
# logging properties      #
#                         #
###########################

logging:
  level:
    root: INFO
    com.santalucia: DEBUG
    org.springframework: INFO
    #org.springframework.web.servlet: DEBUG
    #org.springframework.security: DEBUG
    #org.springframework.web.client: DEBUG
    #trazas para mostrar los errores de login debido a que salen en modo debug
    org.springframework.security.oauth2.server.resource: DEBUG
