DROP TABLE IF EXISTS cacetrafec;


CREATE TABLE cacetrafec (
  ccentrab INT AUTO_INCREMENT  PRIMARY KEY,
  xcacetra VARCHAR(250) NOT NULL,
  finvaldt DATE DEFAULT NULL,
  ffivaldt DATE DEFAULT NULL,
  fregilog DATE DEFAULT NULL
);
