on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
    steps:
      - name: Checkout of the project
        uses: actions/checkout@v5
      
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Compile project
        run: mvn -s ./.m2/settings.xml clean package
      
      - name: generate image
        run: docker build -t docker.io/actraiser/example-11:latest .
      